# bundler_args: "--without development"
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby
gemfile:
  - gemfiles/actionpack-3.0.x.gemfile
  - gemfiles/actionpack-3.1.x.gemfile
