bundler_args: --without development
rvm:
  - 1.8.7-p334
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
gemfile:
  - gemfiles/Gemfile.actionpack-3.0.x
  - gemfiles/Gemfile.actionpack-3.1.x
script: "bundle exec rake spec"
