# This file was generated by Appraisal

source "http://rubygems.org"

gem "ruby-prof", "~> 0.9.2", :platforms=>[:mri_18, :mri_19]
gem "rb-fsevent", "~> 0.3.9", :platforms=>[:mri_18, :mri_19]
gem "actionpack", "~> 3.0"
gem "i18n", "~> 0.5.0"

gemspec :path=>"../"